### GET request to example server
POST http://localhost:8080/
Content-Type: text/plain

https://practicum.yandex.ru
###
POST http://localhost:8080/api/shorten
Content-Type: application/json

{
  "url": "https://practicum.yandex.ru"
}
###

GET http://localhost:8080/h
Content-Type: text/plain
###

PATCH http://localhost:8080/qweuoqiweuoiq_/*weu/kdalsdk;las?qweoipoq=73817
Content-Type: text/plain

###
POST http://localhost:8080
Content-Type: text/plain

/qweuoqiweuoiq_/*weu/kdalsdk;las?qweoipoq=73817

###
GET http://localhost:8080/ping
Content-Type: text/plain

###
POST http://localhost:8080/api/shorten/batch HTTP/1.1
Content-Type: application/json

[{"correlation_id":"4ea23c53-045e-44ec-b06a-0eef5aa37981","original_url":"http://jgjalx.net/eif0st/ffhhovmb0/or40rhnlx"},{"correlation_id":"659e162b-ec5d-46b2-a1c5-e7eac038eec4","original_url":"http://qlwpd6n1zv.com"}]

###
GET http://localhost:8080/api/user/urls
Content-Type: application/json